Create VerificationDetails
EasyPost/easypost-csharp pull request #140
Opened 2020-02-14 02:46 UTC by rbellow

2021-06-28 21:12 UTC, Justintime50 requested changes
We'll want this file to have the proper extension of `.cs`, can you make this correction and we can take another look?

2021-07-13 17:35 UTC, Justintime50 approved these changes

2021-07-13 18:08 UTC, Sarahbear1926 approved these changes

2021-07-13 18:09 UTC, jontsai approved these changes

2021-07-13 19:38 UTC, merged