add thread-safety note to README
EasyPost/easypost-csharp pull request #161
Opened 2021-07-12 19:25 UTC by Roguelazer

2021-07-12 19:32 UTC, Justintime50 requested changes

2021-07-12 19:32 UTC, Justintime50 commented on README.md
> +NOTE: The EasyPost .NET client library (in p;articular, the `ClientManager` global object) is not threadsafe; do not attempt to perform requests from multiple threads in parallel. This can be particu
Correct `p;articular` to `particular`

2021-07-12 19:37 UTC, Justintime50 approved these changes

2021-07-13 18:07 UTC, jontsai approved these changes

2021-07-13 18:07 UTC, ejachang approved these changes

2021-07-13 18:28 UTC, merged