Fix `GetRates()` function
EasyPost/easypost-csharp pull request #206
Opened 2022-02-08 00:13 UTC by nwithan8

`GetRates()` needs to be a static method, called on the `Shipment` class (i.e. `Shipment.GetRates()` rather than `my_shipment.GetRates()`.

This PR:
- Makes `GetRates()` a static method. Pass in the shipment ID. Returns a list of `Rate` objects.
- Clarifies difference between `Shipment.GetRates()` and `my_shipment.RegenerateRates()`

2022-02-08 20:25 UTC, Justintime50 commented
Let's leave this in draft mode just until we've done the minor version bump on this library. Since this is a breaking change, we'll need to include this in our 2nd batch of updates to follow shortly.

2022-02-23 23:32 UTC, Justintime50 commented
@nwithan8 let's rebase this and mark it ready for review.

2022-02-24 20:46 UTC, Justintime50 commented
@nwithan8 can we fix tests here?

2022-02-24 22:19 UTC, nwithan8 commented
Technically, this is running against the new tests, rather than the old test suite.

2022-02-25 18:38 UTC, Justintime50 requested changes

2022-02-25 18:38 UTC, Justintime50 commented on EasyPost.Net/Order.cs
> +        public void RegenerateRates(Dictionary<string, object> parameters = null)
You can't regenerate rates for an order, only a shipment. You'll want to put this back to what it was in both locations.

2022-03-08 20:48 UTC, nwithan8 commented
It seems this patch accidentally snuck itself into `master` via another PR (likely the test suite). This PR is no longer necessary.

2022-03-08 20:48 UTC, closed without merging