Created examples folder
EasyPost/easypost-csharp pull request #291
Opened 2022-07-06 20:47 UTC by ryannguyen16

# Description

created examples folder and started added examples

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-07-12 18:34 UTC, nwithan8 commented
Looks good so far, will thoroughly review when it's ready.
Make sure your IDE is configured to add an empty line at the end of each file. There's some in here that don't have it (notice the red mark on GitHub diffs)

2022-07-13 21:24 UTC, nwithan8 requested changes

2022-07-13 21:24 UTC, nwithan8 commented on examples/insurances/CreateInsurance.cs
> +
Delete the extra lines at the bottom of this file.

2022-07-13 21:24 UTC, nwithan8 commented on examples/insurances/RetrieveInsuranceList.cs
> +listParams = new Dictionary<string, object>() {
```suggestion
Dictionary<string, object> listParams = new Dictionary<string, object>() {
```
```suggestion
listParams = new Dictionary<string, object>() {
```

2022-07-13 21:24 UTC, nwithan8 commented on examples/pickups/CreatePickup.cs
> +parameters = new Dictionary<string, object>() {
```suggestion
Dictionary<string, object> parameters = new Dictionary<string, object>() {
```

2022-07-13 21:24 UTC, nwithan8 commented on examples/trackers/RetrieveTrackerList.cs
> +var listParams = new Dictionary<string, object>() {
```suggestion
Dictionary<string, object> listParams = new Dictionary<string, object>() {
```

2022-07-18 23:14 UTC, Justintime50 commented
No longer valid since these are moving to the `examples` repo.

2022-07-18 23:14 UTC, closed without merging