Deprecate Insurance refresh method
EasyPost/easypost-csharp pull request #358
Opened 2022-10-13 19:51 UTC by nwithan8

# Description

- Fix and deprecate insurance refresh function that shouldn't have existed in the first place

# Testing

- Add unit test, cassettes for method

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-10-13 19:53 UTC, Justintime50 requested changes

2022-10-13 19:53 UTC, Justintime50 commented on EasyPost.Tests/cassettes/netstandard/shipment/forms.json
> +[
What is this file doing in here?

2022-10-13 19:53 UTC, Justintime50 commented on EasyPost/Models/API/Insurance.cs
> +            await Update<Insurance>(Method.Get, $"insurances/{Id}");
This change requires a CHANGELOG entry please

2022-10-18 20:27 UTC, nwithan8 commented
This has been rolled int #357

2022-10-18 20:27 UTC, closed without merging