[POC] Audit HTTP requests
EasyPost/easypost-csharp pull request #478
Opened 2023-05-18 23:00 UTC by nwithan8

# Description

- New option when configuring a client, allowing users to define an action to call when making an HTTP request. The pre-flight request will be passed into the action, allowing users to view/audit every HTTP request made by the client. Users could then interact with the request as they wish (e.g. logging)

# Testing

- New unit test to confirm action is called during HTTP request execution
- Manual debugging confirms the `HttpRequestMessage` object is complete at this point (shouldn't be missing any headers or data, for example)

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2023-05-19 14:34 UTC, jchen293 approved these changes

2023-05-19 15:13 UTC, Justintime50 reviewed
Would love to see a README entry documenting a simple "how to" use this feature since it won't land in our API docs

2023-05-19 17:18 UTC, Justintime50 commented on README.md
> +    RequestAuditor = myRequestAuditingAction,
thought: I'd love to see a dead simple real example. If I'm looking at this, I wouldn't know what I could do. Can we make it as simple as printing to console in the example so people know exactly how to access the request?

2023-05-19 17:28 UTC, Justintime50 reviewed
Seems fine, though can we elicit feedback from the greater team (and support) on the design? What we don't want to do is full send this when they need more out of it or something different

2023-05-19 20:47 UTC, Justintime50 requested changes
Waiting to hear back from everyone.

2023-06-08 21:40 UTC, nwithan8 commented
Closing for now. If we re-open this, reference the [`IntrospectiveClient` in EasyPost.Extensions](https://github.com/nwithan8/easypost-extensions-dotnet/blob/master/EasyPost.Extensions/Clients/IntrospectiveClient.cs)

2023-06-08 21:40 UTC, closed without merging