[feat] Consolidate SmartRate functions, add recommended ship date function
EasyPost/easypost-csharp pull request #566
Opened 2024-05-23 22:37 UTC by nwithan8

# Description

- Add new `SmartRate` service under beta for interacting with the SmartRate API
  - New `RecommendShipDateByDeliveryDate` function to recommend a ship date based on a delivery date for each shipment rate
  - Updated `EstimateDeliveryDateByShipDate` function to get an estimated delivery date based on a ship date for each shipment rate
  - Existing SmartRate-related functions and classes in `Shipment` service marked as deprecated and will be removed in a future release

The entire service is under beta, although inside it the `EstimatedDeliveryDateByShipDate` and `GetSmartRates` functions in it point to GA endpoints. Only `RecommendShipDateByDeliveryDate` is a new "beta" endpoint.

When the service is promoted to GA, the existing SmartRate functions in the `Shipment` service should be removed.

# Testing

- Unit tests added, updated accordingly
- Cassettes added, re-recorded accordingly

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2024-06-03 21:02 UTC, Justintime50 reviewed
I think this looks good. As discussed, we'll hold off until this goes GA to merge in and release. I feel splitting SmartRate to its own service is a good idea especially as the product matures and more functionality becomes available. Since everything is static now, it doesn't make sense to keep it in the Shipment service because you have to pass in the shipment ID anyway now, it no longer inherently belongs to Shipment.

2024-06-10 16:37 UTC, jchen293 reviewed
Code seems good, just two questions. I will approve when the endpoints are in GA

2024-06-10 16:37 UTC, jchen293 commented on EasyPost/Services/Beta/SmartRateService.cs
> +    public class SmartRateService : EasyPostService
Should this class be out of beta when the endpoints are in GA?

2024-06-10 16:37 UTC, jchen293 commented on EasyPost/Services/Beta/SmartRateService.cs
> +        ///     <a href="https://www.easypost.com/docs/api#retrieve-estimated-delivery-date-and-total-transit-days-across-all-rates-for-a-shipment">Related API documentation</a>.
URL seems incorrect to what this function does, you might want to add a TODO and come back to fix it when API docs is added for this endpoint

2024-07-10 21:30 UTC, Justintime50 commented
I'd like this PR to follow the conventions set in the Python one so the experience is consistent across libs, namely the location of the functions in two separate services (keeping the existing functions in the Shipment service), renaming them, and not overloading the functions even though that's a feature of this language (to ensure consistency).

2024-07-12 18:04 UTC, jchen293 requested changes

2024-07-12 18:04 UTC, jchen293 commented on EasyPost.Tests/ServicesTests/WithParameters/ShipmentServiceTest.cs
> +        }
This unit test needs to be removed as we went with the Python lib approach

2024-07-12 18:04 UTC, jchen293 commented on CHANGELOG.md
> +  - Existing SmartRate-related functions and classes in `Shipment` service marked as deprecated and will be removed in a future release
This needs to be updated as we went with the Python lib approach

2024-07-12 18:04 UTC, jchen293 commented on EasyPost/Models/API/EstimateDeliveryDateForZipPairResult.cs
> +        public List<DeliveryDateForZipPairEstimate>? Estimates { get; set; }
Our API response is `Results`, we should not change it to `Estimates` in C# exclusively, we should be consistent with other libs. This also apply to other fields (from_zip, to_zip, and carriers_without_tint_estimates)

2024-07-12 18:04 UTC, jchen293 commented on EasyPost/Models/API/TimeInTransitDetailsForShipDate.cs
> +    public TimeInTransit? TimeInTransitPercentiles { get; set; }
```suggestion
    [JsonProperty("days_in_transit")]
    public TimeInTransit? DayInTransit { get; set; }
```

2024-07-12 20:23 UTC, nwithan8 commented on EasyPost/BetaClient.cs
> +            ReferralCustomer = new Services.Beta.ReferralCustomerService(this);
We are not going to deprecate or remove those beta functions in this current PR, that's a separate task.

2024-07-12 20:23 UTC, nwithan8 commented on EasyPost/BetaClient.cs
> +        public Services.Beta.ReferralCustomerService ReferralCustomer { get; }
No, it's just to clean up the import by making the import path more explicit.

2024-07-16 18:47 UTC, jchen293 commented on CHANGELOG.md
> +    - Existing SmartRate-related functions and classes in `Shipment` service marked as deprecated and will be removed in a future release
Please update the changelog, the function name doesn't match what we have and we are not deprecating the existing function in `Shipment` service. I will approve once this is addressed

2024-07-16 22:04 UTC, jchen293 approved these changes

2024-07-16 22:06 UTC, merged